name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '6.0.x'
      
      - name: Caching NuGet dependencie
        uses: actions/cache@v3
        with:
            path: ~/.nuget/packages
            # Look to see if there is a cache hit for the corresponding requirements file
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            restore-keys: |
                          ${{ runner.os }}-nuget

      - name: Install dependencies
        run:  |
              dotnet add package Newtonsoft.Json --version 12.0.1
              dotnet restore

      - name: Test with dotnet
        run:  dotnet test --logger trx --results-directory "TestResults"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
            name: dotnet-results
            path: TestResults
                  # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Build
        run:  dotnet build

      - name: run
        run: dotnet myapp.dll

      