name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run:  go get .

      - name: Build and Run Go
        run:  go build

      - name: Test with Go
        run: go test -json > TestResults.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Upload TestResults.json
          path: ./TestResults.json
         