name: Java Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
            architecture: x64

      - name: Restore gradle.properties
        env:
              GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
               mkdir -p ~/.gradle/
               echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
               echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Build the app
        run:  |
              gradle init
              ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
            name: Package
            path: build/libs