name: Java Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-version: 11
          maven-version: 3.9.4

      - name: Check Maven Version
        run: mvn --version
      
      - name: Run the Maven verify phase #Should create pom.xml first
        run: mvn --batch-mode --update-snapshots verify
      
      - name: Create Staging Folder 
        run: mkdir staging

      - name: Copy Jar file to Staging Folder
        run: cp target/*.jar staging

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #       java-version: '17'
      #       distribution: 'temurin'

      # - name: Build with Maven
      #   run: mvn --batch-mode package
      
      # - name: Debug
      #   run: ls -R /home/runner/work

      # - name: Build with Maven
      #   run: mvn --batch-mode package --file pom.xml
      #   run: |
      #        mvn --batch-mode --update-snapshots verify
      #        mkdir staging && cp target/*.jar staging
             
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #       name: Package
      #       path: staging