name: Node.js CI
on: [push]
jobs:
  build_test_run_nodejs:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm ci
      - run: npm --version
      - run: node --version
      - run: npm run build --if-present
      - run: npm test
      - run: node app.js